import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import axios from 'axios'
import { Flex, Grid } from '@chakra-ui/layout'
import ListingCard from './../components/ListingCard'

export default function Home() {
  const [listings, setListings] = useState([])
  console.log(listings)

  useEffect(() => {
    const getData = async () => {
      const res = await axios.get('./api/listings')
      setListings(res.data.listings)
    }
    getData()
  }, [])

  return (
    <Flex h='100vh' direction='column' w='100%'>
      <Head>
        <title>See all listings in your area</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {listings && <ListingsGrid listings={listings} />}
    </Flex>
  )
}

const ListingsGrid = props => {
  return (
    <Grid
      templateColumns='repeat(auto-fit, minmax(250px, 1fr));'
      gap={6}
      p={6}
      w='100%'
    >
      {props.listings.map(listing => (
        <ListingCard key={listing._id} listing={listing} />
      ))}
    </Grid>
  )
}
